 ignoreGeneratedHeader = false
severity = "warning"

[[rule]]
name = "exported"
disabled = false

[[rule]]
name = "package-comments"
disabled = false

[[rule]]
name = "dot-imports"
disabled = false

[[rule]]
name = "var-naming"
disabled = false

[rule.var-naming]
min_length = 2
max_length = 40

[[rule]]
name = "unused-parameter"
disabled = false

[[rule]]
name = "indent-error-flow"
disabled = false

[[rule]]
name = "error-naming"
disabled = false

[[rule]]
name = "context-as-argument"
disabled = false

[[rule]]
name = "waitgroup-by-value"
disabled = false

[[rule]]
name = "cognitive-complexity"
disabled = false

[[rule]]
name = "empty-block"
disabled = false

[[rule]]
name = "unhandled-error"
disabled = false
